export type {
  CategoryId,
  CategorySection,
  CostLine,
  FlightDetails,
  MoneyTotals,
  StayDetails,
  PriceBasis,
  ProposalDetail,
  ProposalSummary,
  StepId,
  TripDetail,
  TripInput,
  TripSummary,
} from "../../../shared/domain.ts";
